
import * as fs from "fs";
import yargs from "yargs";
import * as init from "./lib/init";
import { AtTypes } from "./lib/AtTypes";


main();


async function main() {

    const argv = yargs
        .command("typedoc_publish", "Copy typedoc files to the dest directory",
            (obj) => {
                obj.option('src', {
                    alias: 's',
                    describe: 'source directory',
                    default: './docs'
                }).option('dest', {
                    alias: 'd',
                    describe: "destination directory",
                    default: process.env.HOME + "/public_html/typedoc"
                })

            })
        .command("typedoc_buildFrom@types", "Build a TypeDoc from a @types project",
            (obj) => {
                obj.option('base-dir', {
                    alias: 'b',
                    describe: 'base directory',
                    default: process.env.HOME + '/tmp'
                }).option('dest', {
                    alias: 'd',
                    describe: "destination directory",
                    default: process.env.HOME + "/public_html/typedoc/@types"
                }).option('package', {
                    alias: 'p',
                    describe: "package name",
                    default: "@types/node"
                })

            })
        .command("init", "Initialize a typescript package",
            (y) => {
                y.option('unit_test', {
                    alias: 'u',
                    describe: "Unit test framework",
                    default: 'jest'
                })
            })
        .demandCommand()
        .help()
        .argv;



    // console.log(argv);

    if (argv._[0] === "typedoc_publish") {
        const pkgName = get_package_name();
        await typedoc_publish(pkgName, argv.src as string, argv.dest as string);
    }
    else if (argv._[0] === "typedoc_buildFrom@types") {
        const atTypes = new AtTypes();
        atTypes.publish(argv.package as string, argv["base-dir"] as string, argv.dest as string);
    }
    else if (argv._[0] === "init") {
        switch (argv.unit_test as string) {
            case "jest":
                init.init_with_jest();
                break;
            case "mocha":
                init.init_with_mocha();
                break;
            default:
                break;
        }

    }

}


/** Get package name from a package.json.
 */
function get_package_name() {
    const jsonObject = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
    return jsonObject.name;
}


/** Publishes a typedoc directory to an Web server reacheable directory.
 *
 *
 * @param pkgName A package name string. (e.g. "yourpackage")
 * @param src A source directory string. (e.g. "./docs", where HTML files are generated by typedoc.)
 * @param dest A destination directory string. (e.g. "/home/youraccount/public_html/typedoc/yourpackage")
 */
async function typedoc_publish(pkgName: string, src: string, dest: string): Promise<void> {

    console.log("rm -Rf " + src);
    console.log("npm run typedoc");
    try {
        // if dest/pkgName directory exists
        await fs.promises.access(dest + "/" + pkgName);
        // remove dest/pkgName directory.
        console.log("rm -Rf " + dest + "/" + pkgName);

    } catch (error) { // the directory does not exist.
        // do nothing.
    }
    // copy directory.
    console.log(["cp -R ", src, dest + "/" + pkgName].join(" "));
}


